Another
rugpanov/ship-radar-simulation pull request #3
Opened 2018-08-01 15:45 UTC by focus-on-quality

2018-08-02 07:00 UTC, rugpanov requested changes
Общий комментарий. Сейчас здесь 6 коммитов, хотя должен быть один , максимум два. лично мне все-равно сколько коммитов сделано, если бы 4 и 5е коммитов не перетерали коммит историю того, что было сделано мной. В табе аннотейт я увижу не свои комментарии, а Update code update files. Так не пойдет.

2018-08-02 07:00 UTC, rugpanov commented on ShipRadarSimulation/MainWindow.xaml.cs
> +                {"TargetCourseInGrad", 0}
Представь ситуацию, что мы захотим переименовать какое-нибудь поле. Ни одна иде в мире не сможет провести этот рефакторинг. Магическая строка.

2018-08-02 07:00 UTC, rugpanov commented on ShipRadarSimulation/MainWindow.xaml.cs
> +                    movementParamsKV[fields[i].Name] = double.Parse(fields[i].Text.Replace(',', '.'));
Если бы я читал код, то я бы никогда не предположил, что методе с подобным названием происходит что-то подобное. Этого действия не должно быть в методе validation.

2018-08-02 07:00 UTC, rugpanov commented on ShipRadarSimulation/MainWindow.xaml.cs
> +        private void fieldsValidation(TextBox[] fields, out bool isValid)
Ну это просто гениально. Возвращать значение через out , а не через return. Код высшего разума

2018-08-02 07:00 UTC, rugpanov commented on ShipRadarSimulation/MainWindow.xaml.cs
> +                var targetY = movementParamsKV["TargetDistanceKb"] * Math.Cos(Utils.DegreeToRadian(movementParamsKV["TargetBearingInGrad"]));
Эти строки должны быть вынесены в константы. Как минимум. А лучше в стуркуру, в которой нет констант

2018-08-05 11:14 UTC, focus-on-quality commented on ShipRadarSimulation/MainWindow.xaml.cs
> +        private void fieldsValidation(TextBox[] fields, out bool isValid)
Тут я просто забыл исправить, когда убрал возвращение ссылки массив.

2018-08-12 21:19 UTC, closed without merging